apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: node-app-monitor

  labels:
    release: prometheus


spec:

  selector:
    matchLabels:
      app: node-app


  endpoints:

  - port: http
    path: /metrics
    interval: 30s