apiVersion: v1
kind: Service

metadata:
  name: gitops-demo-service

  labels:
    app: gitops-demo


spec:

  type: LoadBalancer

  selector:
    app: gitops-demo

  ports:

  - name: http
    port: 80
    targetPort: 3000